const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  POINT_ADD_REQUEST: 'POINT_ADD_REQUEST',
  POINT_ADD_SUCCESS: 'POINT_ADD_SUCCESS',
  POINT_ADD_FAILURE: 'POINT_ADD_FAILURE',
  SPEND_CRED_REQUEST: 'SPEND_CRED_REQUEST',
  SPEND_CRED_SUCCESS: 'SPEND_CRED_SUCCESS',
  SPEND_CRED_FAILURE: 'SPEND_CRED_FAILURE',
}

export const spendTypes = {
  FULL: 'FULL',
  SNACK: 'SNACK',
}

export default actionTypes
